name: rielu-site
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DISCORD_BOT_TOKEN: "YourToken"
      DISCORD_GUILD_ID: "YourGuildID"
      DISCORD_TARGET_ROLE_ID: "YourTargetRoleID"
    networks:
      - rielu-site-network

networks:
  rielu-site-network:
    driver: bridge
