apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rielu-site
  namespace: rielu-site
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  rules:
    - host: rieluofficial.uniproject.jp
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rielu-site
                port:
                  number: 3000
  tls:
    - hosts:
        - rieluofficial.uniproject.jp
      secretName: rieluofficial-uniproject-jp-tls
