apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rielu-links
  namespace: rielu-links
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    # 以下の2行を追加
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: rielulinks.uniproject.jp
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rielu-links
                port:
                  number: 3001
  tls:
    - hosts:
        - rieluofficial.uniproject.jp
      secretName: rielulinks-uniproject-jp-tls
