apiVersion: v1
kind: Service
metadata:
  name: rielu-links
  namespace: rielu-links
spec:
  type: ClusterIP  # ここ（selectorと同じ階層）に配置
  ports:
    - name: http
      port: 3001
      targetPort: 3001
      protocol: TCP
  selector:
    app: rielu-links
