apiVersion: v1
kind: Service
metadata:
  name: rielu-site
  namespace: rielu-site
spec:
  type: ClusterIP  # ここ（selectorと同じ階層）に配置
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: rielu-site